### ISSUE TITLE
Decide whether to include `title`, `short_title`, and `mdn_url` in recipes

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#203]
All pages have three front matter items that are currently not listed in the recipe: `title`, `short_title`, `mdn_url`.

We should decide whether to keep them in the recipe or not.

@Elchi3 :
> I think we don't need these 3 in the recipes. Maybe we should see them as things you'll always need no matter what kind of content you're creating, so I think I would see them de-coupled from individual page recipes, but as "basic requirements" for any page.

@ddbeck :
> I'd say yes to including the three "redundant" ingredients. In this recipe metaphor, the recipe card should have all the ingredients. The recipes in this case serve as a kind of documentation: here's what you need to have a valid document. Plus, it reduces special cases for tooling: the linter, for example, doesn't have to know anything about global ingredients, if each recipe completely accounts for the ingredients.

FWIW I think I agree with Daniel here. I'm not sure whether they should be in `body`:

```
related_content: /en-US/...
body:
    - meta.title
    - meta.short_title?
    - meta.mdn_url
    - prose.short_description
    - meta.interactive_example?
    ...
```

... or in a different bit. e.g.:

```
related_content: /en-US/...
meta:
    - title
    - short_title?
    - mdn_url
body:
   - ...
```

...and if we did choose `meta`, if we should call front matter ingredients `data.` not `meta.`:

```
related_content: /en-US/...
meta:
    - title
    - short_title?
    - mdn_url
body:
    - prose.short_description
    - data.interactive_example?
    ...
```

**Comment by ddbeck** [comment]
@wbamberg that link doesn't seem to go somewhere specific on the PR. Would you mind pasting the relevant discussion into the issue, for each of these issues relating to #197?

**Comment by wbamberg** [comment]
Sorry @ddbeck , apparently links to review comments are not very reliable. I've updated the description.

**Comment by Elchi3** [comment]
> ...and if we did choose `meta`, if we should call front matter ingredients `data.` not `meta.`:

I like this idea a lot!

**Comment by ddbeck** [comment]
I really like that too! I toyed with changing the recipes for the linter and came up with something very similar. If I understand correctly, then if we renamed `meta` to `data` then we'd get something like this?

```yaml
related_content: /en-US/...
data:
    - title
    - short_title?
    - mdn_url
body:
    - prose.short_description
    - data.interactive_example?
    - …
```

For what it's worth, my version went something like this:

```yaml
related_content: /en-US/...
frontmatter:
    - title
    - short_title?
    - mdn_url
    - interactive_example?
    - …
prose:
   - short_description
   - overview
   - attributes_text?
   - …
   - *
body:
    - prose.short_description
    - frontmatter.interactive_example?
    - …
```

The main difference was that `frontmatter` (a.k.a `meta` or `data`) and `prose` enumerated what was required, optional, and permissible, while `body` provided an order for the built content.
