### ISSUE TITLE
javascript-namespace recipe

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#294]
We talked yesterday about having a separate page type for JS namespaces. This issue summarises our conversation as I understood it.

A namespace is distinguished from just a class because it is not instantiable. So for example, [`Math`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math), [`JSON`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON), [`Intl`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl), and [`WebAssembly`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly) would all be namespaces, not classes.

Some (but not all) namespaces also define constructors for other objects. For example, [`Intl.Collator()`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator) and [`WebAssembly.Memory()`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory).

In terms of recipes, it seems like [javascript-class.yaml](https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-class.yaml) would be mostly unchanged except that I guess `data.class_constructor` would be made mandatory. Then there would be a new recipe "javascript-namespace.yaml" which could look something like:

```yaml
related_content: related_content/javascript.yaml
data:
  - title
  - short_title?
  - mdn_url
body:
  - prose.short_description
  - data.interactive_example?
  - prose.description?
  - data.classes?
  - data.static_properties?
  - data.static_methods?
  - data.instance_properties?
  - data.instance_methods?
  - prose.*
  - data.examples
  - data.specifications
  - data.browser_compatibility
  - prose.see_also
```

...so `data.classes?` is used to list any constructor defined in the namespace, like [`Intl.Collator()`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator). Or would `data.class_constructors?` be better, or is that confusingly too close to the [javascript-class](https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-class.yaml) recipe?

@Elchi3 , @ddbeck , any opinions?
